# Generated by Django 3.2.8 on 2021-10-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisorapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='password_2021', max_length=100),
            preserve_default=False,
        ),
    ]
