# Generated by Django 3.2.8 on 2021-10-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisorapi', '0002_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('adName', models.CharField(max_length=100)),
                ('adProfilePictureURL', models.TextField()),
                ('adId', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
    ]
