# Generated by Django 3.2.8 on 2021-10-31 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisorapi', '0003_advisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisorBookingTrans',
            fields=[
                ('whoBooked', models.CharField(max_length=100)),
                ('whichAdvisor', models.CharField(max_length=100)),
                ('bookingId', models.AutoField(primary_key=True, serialize=False)),
                ('bookingDateTime', models.DateTimeField()),
            ],
        ),
    ]
