# Generated by Django 3.2.8 on 2021-11-02 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advisorapi', '0004_advisorbookingtrans'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisorBooking',
            fields=[
                ('bookingId', models.AutoField(primary_key=True, serialize=False)),
                ('bookingDateTime', models.DateTimeField()),
                ('whichAdvisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisorapi.advisor')),
                ('whoBooked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisorapi.user')),
            ],
        ),
    ]
