# Generated by Django 3.2.8 on 2021-11-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisorapi', '0005_advisorbooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advisor',
            name='adName',
        ),
        migrations.AlterField(
            model_name='advisor',
            name='adId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
