# Generated by Django 3.2.8 on 2021-11-02 11:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('advisorapi', '0006_auto_20211102_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor',
            name='adName',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
