# Generated by Django 3.2.8 on 2021-11-02 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advisorapi', '0008_alter_advisorbookingtrans_whichadvisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisorbookingtrans',
            name='whoBooked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisorapi.user'),
        ),
    ]
